### ISSUE TITLE
STM32 EMAC default configuration issue

### ISSUE THREAD

**Issue by jeromecoutant** [PelionIoT/mbed-cloud-client-example#65]
Hi

Note that STM_EMAC target in
https://github.com/ARMmbed/mbed-cloud-client-example/blob/2278a25d10a9eb01f66f1250b028c73295634930/mbed_app.json#L24
has disappeared since mbed-os-5.14.2

https://github.com/ARMmbed/mbed-os/pull/11536

**Comment by jeromecoutant** [comment]
@teetak01

**Comment by teetak01** [comment]
Hi @jeromecoutant thanks for the pointer. I had not noticed that change in the OS.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-4140

**Comment by teetak01** [comment]
This was fixed as part of 4.5.0 release.
